sudo: required
services:
  - docker
language: minimal

env:
  global:
    - unit_test=/app/.docker/run_unit_tests.sh
    - examples_test=/app/.docker/run_examples_test.sh

jobs:
  allow_failures:
    - stage: debian stretch py2 unit tests
  include:
    - stage: build base debian stretch
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t $DOCKER_USERNAME/gpopup:debian_stretch -f .docker/debian_stretch/Dockerfile .
        - docker images
        - docker push $DOCKER_USERNAME/gpopup:debian_stretch
    - stage: debian stretch py3
      env: DNAME=debian_stretch_py3
      script:
        - docker build --build-arg DOCKER_USERNAME=$DOCKER_USERNAME -t gpopup:$DNAME -f .docker/$DNAME/Dockerfile .
        - docker run --tty gpopup:$DNAME $unit_test
    - # stage: debian stretch py3
      env: DNAME=debian_stretch_py3
      script:
        - docker build --build-arg DOCKER_USERNAME=$DOCKER_USERNAME -t gpopup:$DNAME -f .docker/$DNAME/Dockerfile .
        - docker run --tty gpopup:$DNAME $examples_test
    - stage: debian stretch py2 unit tests
      env: DNAME=debian_stretch_py2
      script:
        - docker build --build-arg DOCKER_USERNAME=$DOCKER_USERNAME -t gpopup:$DNAME -f .docker/$DNAME/Dockerfile .
        - docker run --tty gpopup:$DNAME $unit_test

notifications:
  email: false
